return {
  "nvim-treesitter/nvim-treesitter",
  keys = {
    { "<c-i>", desc = "Increment selection" },
    { "<bs>", desc = "Decrement selection", mode = "x" },
  },
  opts = {
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = "<C-i>",
        node_incremental = "<C-i>",
        scope_incremental = false,
        node_decremental = "<bs>",
      },
    },
    ensure_installed = {
      "bash",
      "c",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
      "rust",
    },
  },
}
